@startuml Jarvis - Eduardo Guilarducci, XP Educação - Projeto de Arquitetura de Software
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml



 LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama de Container para o sistema Jarvis - Eduardo Guilarducci, XP Educação - Projeto de Arquitetura de Software

Person(contador, Contador, "Contador ou Analista Contábil")
Person_Ext(cliente, Cliente, "Adminstrativo Financeiro ou Contábil - Recebe Notas Fiscais para procedimentos internos e usa informações via Analista Contábil")

System_Ext(bitrix, "Bitrix","Sistema de autenticação OAuth2 externo")
System_Ext(migrate, "Invooicy","Sistema de Emissão de Notas Fiscais")
System_Ext(pjbank, "PJBank","Sistema bancário digital")
System_Ext(email, "E-Mail", "Sistema interno de E-mail(GMail)")
System_Ext(s3,"AWS S3", "Armazena os arquivos binários (PDF) das Notas Fiscais e espelhos emitidos.")

System(c1, "System","Jarvis - Sistema Contábil para efetuar agendamentos de contas a pagar e receber, emissão de Notas Fiscais e Conciliação Bancária.") 

Rel(contador, c1, "Efetua agendamentos de contas a pagar e receber, emissão de Notas Fiscais e Conciliação Bancária", "web e mobile usando")
Rel(c1, bitrix, "Autentica e autoriza em", "HTTPS")
Rel(c1, migrate, "Emite e cancela Notas fiscais usando", "HTTPS")Rel(c1, pjbank, "Importa transações bancárias (extrato) de", "HTTPS")
Rel(c1, email, "Envia comunicação via", "HTTPS")
Rel(c1, s3, "Armazena arquivos binários de Notas Fiscais (PDF) em", "HTTPS")
Rel(c1, pjbank, "Importa movimentações financeiras de", "HTTPS")


Rel_Back(cliente, email, "Envia comunicação para")

@enduml